### PR TITLE
Include a User Agent header when making requests

### PR DESCRIPTION
**Pull request by samgiles**
Sched 500s without a User Agent now :(.

r? @arcturus

### CODE REVIEW

**Comment by wilsonpage** [comment]
- Why has this only just started happening? I didn't think the metatdata-service hit Sched servers directly as we use the sched-adaptor service.
- Should we be using [this UA](https://github.com/mozilla-magnet/magnet-metadata-service/blob/master/config.json#L6)?

**Comment by arcturus** [comment]
It will hit if the url is directly the sched one.

I think is a good idea to use a UA, ideally the metadata server should receive it as parameter, but so far, being magnet the only client, I would use a chrome UA.

**Comment by arcturus** [comment]
+1 to use the UA in the configuration.

**Comment by wilsonpage** [comment]
> It will hit if the url is directly the sched one.

@arcturus I don't follow. If we detect sched venue URLs they get adapted, no*? 

\* with Spanish accent

**Comment by samgiles** [comment]
Updated to use config user agent - I missed that.

**Comment by arcturus** [comment]
> @arcturus I don't follow. If we detect sched venue URLs they get adapted, no*? 

Yes and no, right now we are hard coding on the clients that adaptor. But if you try to use the metadata server without the client you will get the 500 error, which is bad :), and definitely can happen with other web pages. Right \* ?
- trying my British accent but failing ;)

**Comment by samgiles** [comment]
Either way, we need to make requests with a `User-Agent` header.  It just super annoying that Sched 500s if you don't set a valid UA header.

**Comment by arcturus** [comment]
oh yes, r+!

**Pull request merged**
