### PR TITLE
Adding a few more ESLint rules and fixes

### PR DESCRIPTION
**Pull request by pdehaan**
Nothing too fun or interesting, just a few more boring rules to enforce missing semi-colons and blank lines at end of files. Most of these are warnings, but we can dial them up to errors in future PRs if we want to fail Travis-CI on ESLint violations.

The _real_ fun [and disruption] starts if we choose to turn on the `no-var` and `prefer-const` rules.

### CODE REVIEW

**Comment by wilsonpage** [comment]
I'm a fan of all these chances except `"curly"`. I like single-line `if` :)

**Comment by arcturus** [comment]
I'm a great fan of curly :) :) (it's my java past )

**Comment by wilsonpage** [comment]
> I'm a great fan of curly :) :) (it's my java past )

If you leave Link you can have `"curly"` :)

**Comment by samgiles** [comment]
+1 for curly. 👍 (sorry @wilsonpage)

**Comment by wilsonpage** [comment]
😠

**Pull request merged**
